on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - run: docker login --username "$DOCKER_USER" --password "$DOCKER_PASS" ghcr.io
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
    - uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        build-args: GOOGLE_CLOUD_GO_VERSION=23c02d92c7a1747068eb1fc57dddbad23907d614
        tags: |
          ghcr.io/getsentry/cbtemulator:${{ github.sha }}
          ghcr.io/getsentry/cbtemulator:latest
